- hosts: localhost
  become: true
  tasks:
  - name: install rabbitmq to hosts machine
    apt:
      name: rabbitmq-server 
      state: present
  - name: Download the cookie
    fetch:
      src: /var/lib/rabbitmq/.erlang.cookie
      dest: rabbitmqcookie
      flat: yes

- hosts: node01  # for node01
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    hosts_file: "filesr/hosts01"
    etc_hosts_file: "/etc/hosts"
  tasks:
  - name: update_cache
    apt:
      update_cache: yes

  - name: copy the hosts file for node01
    copy:
      src: "{{hosts_file}}"
      dest: "{{etc_hosts_file}}"
      mode: "0644"
      
  - name: install rabbitmq to hosts machine
    apt:
      name: rabbitmq-server 
      state: present

  - name: stop rabbitmq server
    command: "sudo systemctl stop rabbitmq-server"

  - name: Copy cookie file to server 
    copy:
      src: rabbitmqcookie
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: '0644'

  - name: start rabbitmq-server 
    command: "sudo systemctl start rabbitmq-server"

  - name: stop rabbitmq app
    command: "sudo rabbitmqctl stop_app"
  
  - name: join the main cluster
    command: "sudo rabbitmqctl join_cluster rabbit@main"
  
  - name: start rabbitmq app
    command: "sudo rabbitmqctl start_app"


- hosts: node02  # for node01
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    hosts_file: "filesr/hosts02"
    etc_hosts_file: "/etc/hosts"
  tasks:
  - name: update_cache
    apt:
      update_cache: yes

  - name: copy the hosts file for node01
    copy:
      src: "{{hosts_file}}"
      dest: "{{etc_hosts_file}}"
      mode: "0644"
      
  - name: install rabbitmq to hosts machine
    apt:
      name: rabbitmq-server 
      state: present

  - name: stop rabbitmq server
    command: "sudo systemctl stop rabbitmq-server"

  - name: Copy hosts file to server 
    copy:
      src: rabbitmqcookie
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: '0644'

  - name: start rabbitmq-server 
    command: "sudo systemctl start rabbitmq-server"

  - name: stop rabbitmq app
    command: "sudo rabbitmqctl stop_app"
  
  - name: join the main cluster
    command: "sudo rabbitmqctl join_cluster rabbit@main"
  
  - name: start rabbitmq app
    command: "sudo rabbitmqctl start_app"