- hosts: localhost
  become: true
  tasks:
  - name: update cache
    apt:
      update_cache: yes

  - name: install rabbitmq with it dependencies
    shell: "sh /home/ubuntu/files/install.sh"

  - name: Download the cookie
    become: true
    shell: "cat /var/lib/rabbitmq/.erlang.cookie > rabbitmqcookie"
  

  
  

- hosts: node02  # for node02
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    hosts_file: "filesr/hosts01"
    etc_hosts_file: "/etc/hosts"
  tasks:
  - name: update_cache
    apt:
      update_cache: yes

  - name: copy the hosts file for node01
    copy:
      src: "{{hosts_file}}"
      dest: "{{etc_hosts_file}}"
      mode: "0644"
  
  - name: copy the rabbitmq instalation script
    copy:
      src: install.sh
      dest: /home/ubuntu/install.sh

      
  - name: install rabbitmq to hosts machine
    shell: "sh /home/ubuntu/install.sh"

  - name: stop rabbitmq server
    command:  "sudo systemctl stop rabbitmq-server"
   

  - name: Copy cookie file to server 
    copy:
      src: rabbitmqcookie
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: '0644'

  - name: Change owner of .erlang.cookie
    become: true
    become_user: root
    command: chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie

  - name: Set permissions of .erlang.cookie
    become: true
    become_user: root
    command: chmod 600 /var/lib/rabbitmq/.erlang.cookie


  - name: start rabbitmq-server 
    command: "sudo systemctl start rabbitmq-server"

  - name: stop rabbitmq app
    command: "sudo rabbitmqctl stop_app"
  
  - name: join the main cluster
    command: "sudo rabbitmqctl join_cluster rabbit@node01"
  
  - name: start rabbitmq app
    command: "sudo rabbitmqctl start_app"


- hosts: node03  # for node02
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    hosts_file: "filesr/hosts02"
    etc_hosts_file: "/etc/hosts"
  tasks:
  - name: update_cache
    apt:
      update_cache: yes

  - name: copy the hosts file for node01
    copy:
      src: "{{hosts_file}}"
      dest: "{{etc_hosts_file}}"
      mode: "0644"
  
  - name: copy the rabbitmq instalation script
    copy:
      src: install.sh
      dest: /home/ubuntu/install.sh

      
  - name: install rabbitmq to hosts machine
    shell: "sh /home/ubuntu/install.sh"

  - name: stop rabbitmq server
    command:  "sudo systemctl stop rabbitmq-server"
   

  - name: Copy cookie file to server 
    copy:
      src: rabbitmqcookie
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: '0644'

  - name: Change owner of .erlang.cookie
    become: true
    become_user: root
    command: chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie

  - name: Set permissions of .erlang.cookie
    become: true
    become_user: root
    command: chmod 600 /var/lib/rabbitmq/.erlang.cookie


  - name: start rabbitmq-server 
    command: "sudo systemctl start rabbitmq-server"

  - name: stop rabbitmq app
    command: "sudo rabbitmqctl stop_app"
  
  - name: join the main cluster
    command: "sudo rabbitmqctl join_cluster rabbit@node01"
  
  - name: start rabbitmq app
    command: "sudo rabbitmqctl start_app"

- hosts: localhost
  become: true
  tasks:
  - name: Add admin user
    shell: "sudo rabbitmqctl add_user admin AdminPassRabbitMQ"
  
  - name: Set user tags for admin
    shell: "sudo rabbitmqctl set_user_tags admin administrator"
  
  - name: Set necessary management
    shell: sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*" 
  
  - name: add vhost
    shell: sudo rabbitmqctl add_vhost app-qa1

  - name: enable rabbitmq management
    shell: sudo rabbitmq-plugins enable rabbitmq_management


- hosts: node02  # for node02
  become: yes
  become_user: root
  remote_user: ubuntu
  tasks:
  - name: enable rabbitmq management
    shell: sudo rabbitmq-plugins enable rabbitmq_management 

- hosts: node03  # for node02
  become: yes
  become_user: root
  remote_user: ubuntu
  tasks:
  - name: enable rabbitmq management
    shell: sudo rabbitmq-plugins enable rabbitmq_management 